vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("i", "<S-Up>", "<Esc>v<Up>")
vim.keymap.set("i", "<S-Down>", "<Esc>v<Down>")
vim.keymap.set("i", "<S-Left>", "<Esc>v<Left>")
vim.keymap.set("i", "<S-Right>", "<Esc>v<Right>")
vim.keymap.set("v", "<C-c>", "y<Esc>i")
vim.keymap.set("i", "<C-v>", "<Esc>pi")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("i", "<C-f>", "<Esc>/")
vim.keymap.set("n", "<C-f>", "/")
vim.keymap.set("v", "<C-f>", "<Esc>/")
vim.keymap.set("i", "<C-t>", "<Esc>gd")
vim.keymap.set("i", "<C-z>", "<Esc>ui")
